# Generated by Django 3.1.3 on 2020-12-09 08:56

import django.core.validators
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(help_text='Enter the Names of Album Artists', max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(help_text='Enter the Album Genre', max_length=50),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.FileField(default='', upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(help_text='Enter the Album Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.DateField(help_text='Enter Album Release Year'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(help_text='Enter the Names of Song Artists', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(help_text='Enter the Song Genre', max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(help_text='Enter the Song Title', max_length=100),
        ),
    ]
