# Generated by Django 3.1.3 on 2021-03-14 13:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20201209_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the Album Title', max_length=100)),
                ('artist', models.CharField(help_text='Enter the Names of Album Artists', max_length=100)),
                ('genre', models.CharField(help_text='Enter the Album Genre', max_length=50)),
                ('year', models.DateField(help_text='Enter Album Release Date with Format: YYYY-MM-DD ')),
                ('image', models.FileField(default='', upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'webp', 'jpeg'])])),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.FileField(default='', upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'webp', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.DateField(help_text='Enter Album Release Date with Format: YYYY-MM-DD '),
        ),
        migrations.CreateModel(
            name='Plist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the Song Title', max_length=100)),
                ('artist', models.CharField(help_text='Enter the Names of Song Artists', max_length=100)),
                ('genre', models.CharField(help_text='Enter the Song Genre', max_length=20)),
                ('sfile', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp3', 'mp4', 'aac'])])),
                ('image', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
                ('al_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.palbum')),
            ],
        ),
    ]
